# Cities with population over 50000
SELECT DISTINCT ?cityLabel ?countryLabel ?countryISO ?population  WHERE {
  {?city (wdt:P31/wdt:P279*) wd:Q515 . }
  UNION
  {?city (wdt:P31/wdt:P279*) wd:Q3957 .}
  ?city wdt:P17 ?country;
  
  wdt:P1082 ?population .
  FILTER(?population > 50000 )
  
  ?country wdt:P297 ?countryISO;

  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}
ORDER BY ASC(?countryLabel) ASC(?cityLabel)
